# Generated by Django 3.1.2 on 2020-10-04 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timedashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timing',
            old_name='curr_project',
            new_name='projects',
        ),
        migrations.AlterField(
            model_name='timing',
            name='end',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='timing',
            name='start',
            field=models.DateTimeField(null=True),
        ),
    ]
