# Generated by Django 3.1.2 on 2020-10-04 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timedashboard', '0002_auto_20201004_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timing',
            name='start',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
