# Generated by Django 3.1.2 on 2020-10-04 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timedashboard', '0003_auto_20201004_1519'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timing',
            old_name='projects',
            new_name='project',
        ),
    ]
